### ISSUE TITLE
Guix package: tests fail: module 'conda_package_handling.cli' has no attribute 'cli'

### ISSUE THREAD

**Issue by Ambrevar** [conda/conda-package-handling#14]
Hi,
I'm trying to package this for Guix (https://guix.info), but the tests won't pass:

```
running "python setup.py" with command "test" and parameters ()
running test
running egg_info
creating conda_package_handling.egg-info
writing conda_package_handling.egg-info/PKG-INFO
writing dependency_links to conda_package_handling.egg-info/dependency_links.txt
writing entry points to conda_package_handling.egg-info/entry_points.txt
writing requirements to conda_package_handling.egg-info/requires.txt
writing top-level names to conda_package_handling.egg-info/top_level.txt
writing manifest file 'conda_package_handling.egg-info/SOURCES.txt'
reading manifest file 'conda_package_handling.egg-info/SOURCES.txt'
writing manifest file 'conda_package_handling.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 28, in <module>
    'Programming Language :: Python :: 3.6',
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/__main__.py", line 3, in <module>
    cli.cli()
AttributeError: module 'conda_package_handling.cli' has no attribute 'cli'
```
Looking at `cli.py`, there is no `cli` function there, only a main.  I don't know much of Python, but is this expected?

**Comment by msarahan** [comment]
we use pytest to run our tests, and they seem to work fine there.  I'm not sure what's going on here.  Can you use pytest, or not?

**Comment by Ambrevar** [comment]
Thanks, that works!

I now have 5 failing tests:

```
tests/test_api.py::test_api_extract_tarball_implicit_path PASSED         [ 10%]
tests/test_api.py::test_api_tarball_details PASSED                       [ 20%]
tests/test_api.py::test_api_conda_v2_details PASSED                      [ 30%]
tests/test_api.py::test_api_extract_tarball_explicit_path PASSED         [ 40%]
tests/test_api.py::test_api_extract_conda_v2_implicit_path FAILED        [ 50%]
tests/test_api.py::test_api_extract_conda_v2_explicit_path FAILED        [ 60%]
tests/test_api.py::test_api_extract_info_conda_v2 FAILED                 [ 70%]
tests/test_api.py::test_api_transmute_tarball_to_conda_v2 FAILED         [ 80%]
tests/test_api.py::test_api_transmute_conda_v2_to_tarball FAILED         [ 90%]
tests/test_api.py::test_warning_when_bundling_no_metadata PASSED         [100%]

=================================== FAILURES ===================================
___________________ test_api_extract_conda_v2_implicit_path ____________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 40, in test_api_extract_conda_v2_implicit_path
    api.extract(condafile)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 22, in extract
    SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 61, in extract
    _extract_component(fn, file_id, component, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 43, in _extract_component
    _tar_xf(component_filename, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 78, in _tar_xf
    libarchive.extract_file(tarball, flags)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/extract.py", line 69, in extract_file
    with file_reader(filepath) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/read.py", line 85, in file_reader
    ffi.read_open_filename_w(archive_p, path, block_size)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 91, in check_int
    raise archive_error(args[0], retcode)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 75, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Unrecognized archive format (errno=84, retcode=-30, archive_p=10071952)
___________________ test_api_extract_conda_v2_explicit_path ____________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 46, in test_api_extract_conda_v2_explicit_path
    api.extract(tarfile, 'manual_path')
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 22, in extract
    SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 61, in extract
    _extract_component(fn, file_id, component, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 43, in _extract_component
    _tar_xf(component_filename, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 78, in _tar_xf
    libarchive.extract_file(tarball, flags)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/extract.py", line 69, in extract_file
    with file_reader(filepath) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/read.py", line 85, in file_reader
    ffi.read_open_filename_w(archive_p, path, block_size)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 91, in check_int
    raise archive_error(args[0], retcode)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 75, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Unrecognized archive format (errno=84, retcode=-30, archive_p=10118944)
________________________ test_api_extract_info_conda_v2 ________________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 52, in test_api_extract_info_conda_v2
    api.extract(condafile, 'manual_path', components='info')
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 22, in extract
    SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 61, in extract
    _extract_component(fn, file_id, component, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 43, in _extract_component
    _tar_xf(component_filename, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 78, in _tar_xf
    libarchive.extract_file(tarball, flags)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/extract.py", line 69, in extract_file
    with file_reader(filepath) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/read.py", line 85, in file_reader
    ffi.read_open_filename_w(archive_p, path, block_size)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 91, in check_int
    raise archive_error(args[0], retcode)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 75, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Unrecognized archive format (errno=84, retcode=-30, archive_p=10134032)
____________________ test_api_transmute_tarball_to_conda_v2 ____________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 59, in test_api_transmute_tarball_to_conda_v2
    api.transmute(tarfile, '.conda', testing_workdir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 80, in transmute
    _convert(fn)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 72, in _convert
    create(tmp, file_list, _os.path.basename(out_fn), out_folder=out_folder, **kw)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 46, in create
    SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 77, in create
    ext, comp_filter, filter_opts)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 64, in create_compressed_tarball
    options=filter_opts) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/write.py", line 174, in file_writer
    with new_archive_write(format_name, filter_name, options) as archive_p:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/write.py", line 122, in new_archive_write
    getattr(ffi, 'write_add_filter_'+filter_name)(archive_p)
AttributeError: module 'libarchive.ffi' has no attribute 'write_add_filter_zstd'
----------------------------- Captured stderr call -----------------------------
Converting: /tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/data/mock-2.0.0-py37_1000.tar.bz2: 100%|██████████| 1/1 [00:00<00:00, 53.46it/s]
____________________ test_api_transmute_conda_v2_to_tarball ____________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 65, in test_api_transmute_conda_v2_to_tarball
    api.transmute(condafile, '.tar.bz2', testing_workdir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 80, in transmute
    _convert(fn)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 68, in _convert
    extract(fn, dest_dir=tmp)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 22, in extract
    SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 61, in extract
    _extract_component(fn, file_id, component, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 43, in _extract_component
    _tar_xf(component_filename, dest_dir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 78, in _tar_xf
    libarchive.extract_file(tarball, flags)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/extract.py", line 69, in extract_file
    with file_reader(filepath) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/read.py", line 85, in file_reader
    ffi.read_open_filename_w(archive_p, path, block_size)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 91, in check_int
    raise archive_error(args[0], retcode)
  File "/gnu/store/cw765c4xq8ddqz9z4gmjs7xs0id1128n-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/ffi.py", line 75, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Unrecognized archive format (errno=84, retcode=-30, archive_p=10154960)
----------------------------- Captured stderr call -----------------------------
Converting: /tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/data/mock-2.0.0-py37_1000.conda: 100%|██████████| 1/1 [00:00<00:00, 1554.60it/s]
 generated xml file: /tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/junit.xml 
========================== slowest 20 test durations ===========================
0.02s call     tests/test_api.py::test_api_transmute_tarball_to_conda_v2
0.02s call     tests/test_api.py::test_api_extract_tarball_implicit_path
0.01s call     tests/test_api.py::test_api_extract_tarball_explicit_path
0.00s setup    tests/test_api.py::test_api_extract_tarball_implicit_path
0.00s call     tests/test_api.py::test_api_extract_conda_v2_implicit_path
0.00s call     tests/test_api.py::test_api_transmute_conda_v2_to_tarball
0.00s call     tests/test_api.py::test_api_extract_conda_v2_explicit_path
0.00s call     tests/test_api.py::test_api_extract_info_conda_v2
0.00s setup    tests/test_api.py::test_api_extract_conda_v2_explicit_path
0.00s setup    tests/test_api.py::test_warning_when_bundling_no_metadata
0.00s setup    tests/test_api.py::test_api_transmute_conda_v2_to_tarball
0.00s setup    tests/test_api.py::test_api_tarball_details
0.00s setup    tests/test_api.py::test_api_extract_conda_v2_implicit_path
0.00s setup    tests/test_api.py::test_api_transmute_tarball_to_conda_v2
0.00s teardown tests/test_api.py::test_warning_when_bundling_no_metadata
0.00s setup    tests/test_api.py::test_api_extract_info_conda_v2
0.00s setup    tests/test_api.py::test_api_conda_v2_details
0.00s setup    tests/test_api.py::test_api_extract_tarball_explicit_path
0.00s call     tests/test_api.py::test_api_tarball_details
0.00s call     tests/test_api.py::test_api_conda_v2_details
====================== 5 failed, 5 passed in 0.13 seconds ======================
```

Is it possible that this library relies on system programs like `tar` et al.?

**Comment by Ambrevar** [comment]
Or else I suspect that the `testing_workdir` is wrong: Guix packages are built in a chroot, maybe the testing_workdir cannot be set properly and this results in broken path for the input files.

**Comment by msarahan** [comment]
It looks like your libarchive is not built with support for zstd.

**Comment by Ambrevar** [comment]
Hmmm... I've added libarchive as a package dependency (I thought python-libarchive-c would be enough, but apparently not) and now 9 tests pass.  The zstd failure is still here with a libarchive that is linked against zstd:

```
=================================== FAILURES ===================================
____________________ test_api_transmute_tarball_to_conda_v2 ____________________
Traceback (most recent call last):
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/tests/test_api.py", line 59, in test_api_transmute_tarball_to_conda_v2
    api.transmute(tarfile, '.conda', testing_workdir)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 80, in transmute
    _convert(fn)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 72, in _convert
    create(tmp, file_list, _os.path.basename(out_fn), out_folder=out_folder, **kw)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/api.py", line 46, in create
    SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/conda_fmt.py", line 77, in create
    ext, comp_filter, filter_opts)
  File "/tmp/guix-build-python-conda-package-handling-1.1.1.drv-0/source/conda_package_handling/tarball.py", line 64, in create_compressed_tarball
    options=filter_opts) as archive:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/z3m0s18n688sy0ribzv8dbgxzjf4lvqx-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/write.py", line 174, in file_writer
    with new_archive_write(format_name, filter_name, options) as archive_p:
  File "/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/gnu/store/z3m0s18n688sy0ribzv8dbgxzjf4lvqx-python-libarchive-c-2.8/lib/python3.7/site-packages/libarchive/write.py", line 122, in new_archive_write
    getattr(ffi, 'write_add_filter_'+filter_name)(archive_p)
AttributeError: module 'libarchive.ffi' has no attribute 'write_add_filter_zstd'
```

Any idea on how to investigate further?

**Comment by mingwandroid** [comment]
You need to build libarchive better here I'm afraid. It hasn't found zstd

**Comment by Ambrevar** [comment]
Looking at https://github.com/Changaco/python-libarchive-c/blob/master/libarchive/ffi.py#L230 it has no 'zstd' attribute.  Am I depending on the wrong library?

**Comment by msarahan** [comment]
The package from pypi is not built with zstd support.  It's less a property of python-libarchive-c and more the underlying compiled library, libarchive-c.  Our recipe for that is at https://github.com/anacondarecipes/libarchive-feedstock

**Comment by Ambrevar** [comment]
I'm confused (Disclaimer: I don't know much about python).
My Guix' libarchive is built against zstd and it's working fine.

python-libarchive-c does not reference zstd in its source, so I don't understand how it's supposed to work.

@msarahan: The link you've shared only deals with libarchive, right?  It does not change anything for python-libarchive-c, does it?

**Comment by msarahan** [comment]
Right, that link is only libarchive

**Comment by rekado** [comment]
We avoid this problem in Guix by replacing `archive_and_deps` with `archive` in `setup.py`.  Tests are passing, so I think this issue can be closed.
