### ISSUE TITLE
conda hang by conda-package-handling (anaconda2)

### ISSUE THREAD

**Issue by machinewu** [conda/conda-package-handling#38]
My conda update to 4.7.5, and conda-package-handling update to 1.3.11 (`conda update conda`). My PC is Win10 x64 1903.
**I found conda can not install any `.conda` package for it will hang while installing.**

I just modified some code in `conda_fmt.py` and found it hang in this file.
Add some print log in function `_extract_component` in file `conda_fmt.py`
```
def _extract_component(fn, file_id, component_name, dest_dir=os.getcwd()):
    try:
        print("here x1")
        with ZipFile(fn, compression=ZIP_STORED) as zf:
            with utils.TemporaryDirectory() as tmpdir:
                with utils.tmp_chdir(tmpdir):
                    component_filename = _lookup_component_filename(zf, file_id, component_name)
                    if not component_filename:
                        raise RuntimeError("didn't find {} component in {}"
                                           .format(component_name, fn))
                    print("here x2")
                    component_filename = component_filename[0]
                    print("here x3")
                    zf.extract(component_filename)
                    print("here x4")
                    _tar_xf(component_filename, dest_dir)
                    print("here x5")
    except BadZipFile as e:
        raise InvalidArchiveError(fn, str(e))
```

```
(base) C:\Users\machine>conda install --use-local D:\devtool\Anaconda2\pkgs\pip-19.1.1-py27_0.conda -n py2 -vv
DEBUG conda.gateways.logging:set_verbosity(231): verbosity set to 2
DEBUG conda.core.package_cache_data:__init__(604): instantiating ProgressiveFetchExtract with
  *[url=file:///D:/devtool/Anaconda2/pkgs/pip-19.1.1-py27_0.conda]

DEBUG conda.core.package_cache_data:_check_writable(261): package cache directory 'D:\devtool\Anaconda2\pkgs' writable: True
DEBUG conda.core.package_cache_data:_check_writable(261): package cache directory 'D:\devtool\Anaconda2\pkgs' writable: True
DEBUG conda.core.package_cache_data:_make_single_record(313): unable to read D:\devtool\Anaconda2\pkgs\pip-19.1.1-py27_0\info\repodata_record.json
  because IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "D:\devtool\Anaconda2\lib\logging\__init__.py", line 868, in emit
    msg = self.format(record)
  File "D:\devtool\Anaconda2\lib\logging\__init__.py", line 741, in format
    return fmt.format(record)
  File "D:\devtool\Anaconda2\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "D:\devtool\Anaconda2\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file package_cache_data.py, line 324
DEBUG conda.gateways.disk.create:extract_tarball(209): extracting D:\devtool\Anaconda2\pkgs\pip-19.1.1-py27_0.conda
  to D:\devtool\Anaconda2\pkgs\pip-19.1.1-py27_0
here x1
here x2
here x3
here x4
```

Above showing that it will hang in function ` _tar_xf(component_filename, dest_dir)`. Because it have not print `here x5` yet.

In addition, `cph -h` will raise error
```
(base) C:\Users\machine>cph -h
Traceback (most recent call last):
  File "D:\devtool\Anaconda2\Scripts\cph-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\devtool\Anaconda2\lib\site-packages\conda_package_handling\cli.py", line 50, in main
    args = parse_args(args)
  File "D:\devtool\Anaconda2\lib\site-packages\conda_package_handling\cli.py", line 15, in parse_args
    extract_parser = sp.add_parser('extract', help='extract package contents', aliases=['x'])
  File "D:\devtool\Anaconda2\lib\argparse.py", line 1070, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases'
```

**Comment by machinewu** [comment]
I used the archive.dll in anaconda3 (my anaconda3 installation `D:\devtool\Anaconda3\Library\bin`) to replace the corresponding location of anaconda2 (my anaconda2 installation `D:\devtool\Anaconda2\Library\bin`) can solve the stuck problem.
