### ISSUE TITLE
UnboundLocalError: local variable 'out' referenced before assignment

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-package-handling#54]
When `SUPPORTED_EXTENSIONS[ext].create(...)` (https://github.com/conda/conda-package-handling/blob/master/src/conda_package_handling/api.py#L58) fails, I get an `UnboundLocalError: local variable 'out' referenced before assignment` because the name `out` that [line 85](https://github.com/conda/conda-package-handling/blob/master/src/conda_package_handling/api.py#L85) is referring to, does not yet exist.

**Comment by mariusvniekerk** [comment]
This also occurred here

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=106194&view=logs&j=7ccfbd65-6b56-5fef-0b9c-2d2771a32ccc&t=536d24a5-8153-5e3b-b96c-8f57c17c5677

This might arise from a some issues with weird filenames?

```

Fixing permissions
Packaged license file/s.
WARNING: Detecting which files contain PREFIX is slow, installing ripgrep makes it faster. 'conda install ripgrep'
WARNING:conda.gateways.disk.delete:Could not remove or rename C:\Users\VSSADM~1\AppData\Local\Temp\tmpnks_r17e\go-nocgo-1.13.5-h17abafa_0.tar.bz2.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename C:\Users\VSSADM~1\AppData\Local\Temp\tmpnks_r17e\go-nocgo-1.13.5-h17abafa_0.tar.bz2.  Please remove this file manually (you may need to reboot to free file handles)
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\conda_package_handling\api.py", line 82, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "C:\Miniconda\lib\site-packages\conda_package_handling\tarball.py", line 145, in create
    '.tar.bz2', 'bzip2')
  File "C:\Miniconda\lib\site-packages\conda_package_handling\tarball.py", line 78, in create_compressed_tarball
    _create_libarchive(fullpath, files, compression_filter, filter_opts)
  File "C:\Miniconda\lib\site-packages\conda_package_handling\tarball.py", line 64, in _create_libarchive
    archive_utils.create_archive(fullpath, files, compression_filter, filter_opts)
  File "C:\Miniconda\lib\site-packages\conda_package_handling\archive_utils.py", line 29, in create_archive
    raise ArchiveCreationError(message)
conda_package_handling.exceptions.ArchiveCreationError: : Couldn't visit directory while writing file: go\test\fixedbugs\issue27836.dir\�foo.go

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2344, in build_tree
    notest=notest,
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1643, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1028, in bundle_conda
    basename + ext, out_folder=tmp)
  File "C:\Miniconda\lib\site-packages\conda_package_handling\api.py", line 85, in create
    if _os.path.isfile(out):
UnboundLocalError: local variable 'out' referenced before assignment

```

**Comment by sscherfke** [comment]
The cause of my issue were compilation or linking issues with bzip2.  This is why I didn't even get an error message from libarchive.

/close

**Comment by thomas-mueller** [comment]
I have the same problem:
```
INFO:conda_build.build:Packaging dstk
INFO conda_build.build:build(1571): Packaging dstk
source tree in: /opt/conda/conda-bld/dstk_1598256196268/work
Resource usage statistics from building dstk:
   Process count: 1
   CPU time: Sys=0:00:00.0, User=0:00:00.0
   Memory: 1.3M
   Disk usage: 17.7K
   Time elapsed: 0:00:02.1
Packaging dstk
fatal: No names found, cannot describe anything.
INFO:conda_build.build:Packaging dstk-0+untagged.54.g6b6c70c2.dirty-py36_1
INFO conda_build.build:bundle_conda(891): Packaging dstk-0+untagged.54.g6b6c70c2.dirty-py36_1
Packaging dstk-0+untagged.54.g6b6c70c2.dirty-py36_1
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
compiling .pyc files...
number of files: 69
Fixing permissions
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/api.py", line 82, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/tarball.py", line 145, in create
    '.tar.bz2', 'bzip2')
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/tarball.py", line 78, in create_compressed_tarball
    _create_libarchive(fullpath, files, compression_filter, filter_opts)
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/tarball.py", line 64, in _create_libarchive
    archive_utils.create_archive(fullpath, files, compression_filter, filter_opts)
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/archive_utils.py", line 29, in create_archive
    raise ArchiveCreationError(message)
conda_package_handling.exceptions.ArchiveCreationError: Failed to clean up compressor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1643, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1028, in bundle_conda
    basename + ext, out_folder=tmp)
  File "/opt/conda/lib/python3.6/site-packages/conda_package_handling/api.py", line 85, in create
    if _os.path.isfile(out):
UnboundLocalError: local variable 'out' referenced before assignment
```
Actually, this problem only occurs when I run the `conda build` step in a Gitlab pipeline. It runs locally and during building a docker image (also within a Gitlab pipeline). I checked that I do exactly the same in all three cases and that versions of relevant packages are all the same. The output folder is created before the `conda build` step. What else could I try? I am using conda build version 3.18.11 with python 3.6.
