### ISSUE TITLE
test_secure_refusal_to_extract_abs_paths is failing

### ISSUE THREAD

**Issue by opoplawski** [conda/conda-package-handling#59]
I'm seeing the following building the Fedora python-conda-package-handling package:
```
+ py.test-3.8 -v tests
============================= test session starts ==============================
platform linux -- Python 3.8.1, pytest-4.6.9, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/orion/fedora/python-conda-package-handling/conda-package-handling-1.6.0, inifile: setup.cfg
plugins: cov-2.8.1, mock-1.10.4, pyfakefs-3.5.8
collecting ... collected 22 items
...
___________________ test_secure_refusal_to_extract_abs_paths ___________________
Traceback (most recent call last):
  File "/home/orion/fedora/python-conda-package-handling/conda-package-handling-1.6.0/tests/test_api.py", line 193, in test_secure_refusal_to_extract_abs_paths
    api.extract('pinkie.tar.bz2')
  File "/usr/lib/python3.8/site-packages/_pytest/python_api.py", line 736, in __exit__
    fail(self.message)
  File "/usr/lib/python3.8/site-packages/_pytest/outcomes.py", line 119, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'conda_package_handling.exceptions.InvalidArchiveError'>
- generated xml file: /home/orion/fedora/python-conda-package-handling/conda-package-handling-1.6.0/junit.xml -
```
Looks like we have finally caught up to 2019-12-01 :)

**Comment by Bindiytm** [comment]
Getting the same issue, is there any resolution for this?
