### ISSUE TITLE
Confusing error message when running out of disk space

### ISSUE THREAD

**Issue by chrisburr** [conda/conda-package-handling#62]
When running out of disk space, conda-package-handing prints an unclear message and leaves a corrupt tarball when using libarchive behind the scenes:

```
Package at /home/conda/feedstock_root/build_artifacts/linux-64/root_base-6.20.4-py36h11b598d_2.tar.bz2 did not contain valid index.json data.  Please check the file and remove/redownload if necessary to obtain a valid package.
ERROR:conda_build.index:Package at /home/conda/feedstock_root/build_artifacts/linux-64/root_base-6.20.4-py36h11b598d_2.tar.bz2 did not contain valid index.json data.  Please check the file and remove/redownload if necessary to obtain a valid package.
ERROR conda_build.index:index_subdir(938): Package at /home/conda/feedstock_root/build_artifacts/linux-64/root_base-6.20.4-py36h11b598d_2.tar.bz2 did not contain valid index.json data.  Please check the file and remove/redownload if necessary to obtain a valid package.
A process in the process pool was terminated abruptly while the future was running or pending.
```

Hackily forcing libarchive not to be used (with ` rm $(dirname $(dirname $(which conda)))/lib/python*/site-packages/conda_package_handling/archive_utils_cy*`) causes a clearer error message to be shown:

```
/home/conda/feedstock_root/build_artifacts/root_1587380052181/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh :: text :: include/compiledata.h
include/compiledata.h (text): Patching
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 60, in _create_no_libarchive
    t.add(f)
  File "/opt/conda/lib/python3.7/tarfile.py", line 1944, in add
    self.addfile(tarinfo, f)
  File "/opt/conda/lib/python3.7/tarfile.py", line 1972, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/opt/conda/lib/python3.7/tarfile.py", line 250, in copyfileobj
    dst.write(buf)
  File "/opt/conda/lib/python3.7/bz2.py", line 242, in write
    self._fp.write(compressed)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/api.py", line 82, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 145, in create
    '.tar.bz2', 'bzip2')
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 80, in create_compressed_tarball
    _create_no_libarchive(fullpath, files)
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 60, in _create_no_libarchive
    t.add(f)
  File "/opt/conda/lib/python3.7/tarfile.py", line 2431, in __exit__
    self.fileobj.close()
  File "/opt/conda/lib/python3.7/bz2.py", line 121, in close
    self._fp.write(self._compressor.flush())
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2151, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1531, in bundle_conda
    basename + ext, out_folder=tmp)
  File "/opt/conda/lib/python3.7/site-packages/conda_package_handling/api.py", line 85, in create
    if _os.path.isfile(out):
UnboundLocalError: local variable 'out' referenced before assignment
```

**Comment by jezdez** [comment]
The UnboundLocalError and the surrounding error handling was fixed in #77.
