### ISSUE TITLE
args.out_folder does not exist for all parsers

### ISSUE THREAD

**Issue by beckermr** [conda/conda-package-handling#72]

**Comment by sscherfke** [comment]
```
+ cph create . test.tar.bz2
+ test -f test.tar.bz2
+ cph extract test.tar.bz2
Traceback (most recent call last):
  File "/opt/ownconda/conda-bld/conda-package-handling_1603785198530/_test_env_pl/bin/cph", line 10, in <module>
    sys.exit(main())
  File "/opt/ownconda/conda-bld/conda-package-handling_1603785198530/_test_env_pl/lib/python3.8/site-packages/conda_package_handling/cli.py", line 76, in main
    if args.out_folder:
AttributeError: 'Namespace' object has no attribute 'out_folder'
Tests failed for conda-package-handling-1.7.2-py38_0.tar.bz2 - moving package to /opt/ownconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for conda-package-handling-1.7.2-py38_0.tar.bz2 - moving package to /opt/emsconda/conda-bld/broken
```

**Comment by mingwandroid** [comment]
Thanks, CPH is getting some attention now.
